# Generated by Django 3.1.2 on 2020-11-17 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('dni', models.PositiveIntegerField(unique=True, verbose_name='Cédula/NIT')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre Persona/Asociación')),
                ('contacto', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de Perfil')),
                ('hdv', models.FileField(blank=True, max_length=200, null=True, upload_to='hdv/', verbose_name='Curriculum (Aplicantes)')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('is_empresa', models.BooleanField(default=False, verbose_name='Es Empleador?(Empresa)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('salario', models.PositiveIntegerField()),
                ('horario', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiapp.area')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiapp.ciudad')),
                ('empresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
            },
        ),
        migrations.CreateModel(
            name='aplicantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ofertaaplicada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practiapp.oferta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='aplicantes',
            constraint=models.UniqueConstraint(fields=('ofertaaplicada', 'aplicante'), name='unoporoferta'),
        ),
    ]
