# Generated by Django 3.1.2 on 2020-11-19 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='apply',
            field=models.ManyToManyField(blank=True, null=True, related_name='apply', to=settings.AUTH_USER_MODEL),
        ),
    ]
