# Generated by Django 3.1.2 on 2020-11-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiapp', '0003_auto_20201119_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='apply',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
